services:
  user-service:
    build:
      context: .
      dockerfile: src/UserService/Dockerfile
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - user-data:/data

  schedule-service:
    build:
      context: .
      dockerfile: src/ScheduleService/Dockerfile
    ports:
      - "5002:5002"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - schedule-data:/data
    depends_on:
      - notification-service

  notification-service:
    build:
      context: .
      dockerfile: src/NotificationService/Dockerfile
    ports:
      - "5003:5003"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - notification-data:/data

volumes:
  user-data:
  schedule-data:
  notification-data: